site_name: DPD Pāḷi Courses
docs_dir: "docs"
site_dir: "site"

theme:
  name: material
  language: en
  custom_dir: "tools/ssg/stylesheets"
  palette:
    - scheme: default
      primary: brown
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: brown
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - content.code.copy

extra_css:
  - dpd.css
  - dpd-variables.css
  - extra.css

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables

nav:
  - Home: index.md
  - Beginner Course (BPC):
      - Course Material: bpc/index.md
      - Exercises: bpc_ex/index.md
      - Answer Keys: bpc_key/index.md
  - Intermediate Course (IPC):
      - Course Material: ipc/index.md
      - Exercises: ipc_ex/index.md
      - Answer Keys: ipc_key/index.md

plugins:
  - search
