site_name: DPD Pāḷi Courses
docs_dir: "docs"
site_dir: "site"

theme:
  name: material
  language: en
  custom_dir: "tools/ssg/stylesheets"
  palette:
    - scheme: default
      primary: brown
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: brown
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - content.code.copy

extra_css:
  - dpd.css
  - dpd-variables.css
  - extra.css

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables

nav:
  - Home: index.md
  - Beginner Course (BPC):
    - bpc/index.md
    - bpc/0.1_title.md
    - bpc/0.2_literature.md
    - bpc/0.3_content.md
    - Class 1: bpc/class_1/1_class.md
    - Class 2:
      - bpc/class_2/index.md
      - bpc/class_2/0_content.md
      - bpc/class_2/1_review.md
      - bpc/class_2/2_alphabet.md
      - bpc/class_2/3_decl_nouns.md
      - bpc/class_2/4_home_work.md
  - Intermediate Course (IPC):
    - ipc/index.md
    - ipc/0.1_title.md
    - ipc/0.2_content.md
  - Exercises:
    - bpc_ex/index.md
    - ipc_ex/index.md
  - Answer Keys:
    - bpc_key/index.md
    - ipc_key/index.md

plugins:
  - search
